### ISSUE TITLE
Add support for Django 4.0

### ISSUE THREAD

**Issue by Melevir** [clintonb/django-waffle#417]
It would be great if django-waffle is Django 4.0 compatible.

Sadly, new version of Django dropped a lot of deprecated functions, so update required some actions in django-waffle's code.

Here are two problems:

- NullBooleanField usage in migration (check out #441)
- `ImportError: cannot import name 'url' from 'django.conf.urls'`

This one because `django.conf.urls.url` was removed in Django 4.0 and it's imported in waffle/urls.py.

**Comment by rh0dium** [comment]
Also
- [ ] Remove `default_app_config`

If you need help holler!

**Comment by clintonb** [comment]
@rh0dium a pull request is welcome!

**Comment by Melevir** [comment]
I see that the main branch works fine with django4. Any plans on the PyPI release?

**Comment by clintonb** [comment]
@Melevir feel free to open a pull request that adds test support.

**Comment by Melevir** [comment]
That was my plan, but it turns out, that the only problem, that blocked me from running waffle on django4 was URLs thing, which is resolved in https://github.com/django-waffle/django-waffle/commit/c781c32de8d7e823e54486862ce5f70d2f49da33

What else blocks django-waffle from django4-compatible release? I'll be glad to help.

**Comment by clintonb** [comment]
- [ ] Add explicit test support for 4.0 at https://github.com/django-waffle/django-waffle/blob/master/tox.ini#L19
- [ ] Update classifiers in https://github.com/django-waffle/django-waffle/blob/master/setup.py#L27

**Comment by clintonb** [comment]
Fixed by #421
