### ISSUE TITLE
How do you keep flags in sync across environments?

### ISSUE THREAD

**Issue by elamje** [clintonb/django-waffle#419]
In other words, how do you define flags that should appear in your test and prod environments without needing to manually add them to both.

I can think of at least two ways to do this, but neither seem ideal. I'm curious what solutions others have used to manage flags at deploy time in different environments. 

For context, the way we use flags is to hide frontend and backend code for trunk based development as well as traditional feature flipping for certain users. In practice, each code deploy w/ a new feature has a flag. Since code is coupled to flags, I hope there is an optimal way to ensure flags exist across environments as code moves through them. 

What is the optimal way you've seen this managed in a Django project?

**Comment by clintonb** [comment]
Write a data migration that creates the flag.
