### ISSUE TITLE
Documentation example for custom flag

### ISSUE THREAD

**Issue by TAnas0** [clintonb/django-waffle#420]
The documentation for the custom flag shows an example and it might lead to errors and confusion: https://waffle.readthedocs.io/en/stable/types/flag.html#custom-flag-models

The imported `get_cache` method is not used and the `cache` variable referenced is undefined.

Is there a missing `cache = get_cache()` somewhere? Should be placed outside of the class or defined as a class attribute?

**Comment by dancergraham** [comment]
This looks OK to me with the latest documentation version
