### ISSUE TITLE
Automatically creating switches no longer works in 2.4.0

### ISSUE THREAD

**Issue by davidreynolds** [clintonb/django-waffle#435]
I have `WAFFLE_CREATE_MISSING_SWITCHES=True` in my django settings. Since updating to waffle 2.4.0 this feature is no longer working.

This is the exception being thrown:

`Django.core.exceptions.FieldError: Invalid field name(s) for model Switch: 'everyone'.`

This is the line triggering the exception:
https://github.com/django-waffle/django-waffle/blob/947195bcaff3cadabf005b7f00ba8dfee34b6b3f/waffle/models.py#L61

**Comment by weirdpipo** [comment]
I can confirm, I am having the same issue, I think @clintonb broke it here: https://github.com/django-waffle/django-waffle/blob/fb1ab67b41b4331fdac5a0c560cdc2a96f8a01f3/waffle/models.py#L62

**Comment by clintonb** [comment]
https://github.com/django-waffle/django-waffle/releases/tag/v2.4.1 has been released, and the offending code removed.

**Comment by honzakral** [comment]
My apologies for the original PR that introduced this bug (and thank you, @clintonb, for a quick reaction!), I began work on a more comprehensive solution in #438. Since I am not using `Switch` or `Sample` models I would appreciate another set of eyes and ideas on how to properly test the change.
