### ISSUE TITLE
Support for custom models for switches

### ISSUE THREAD

**Issue by shaun-gallagher-octane** [clintonb/django-waffle#442]
Waffle supports custom models for Flags, which can be specified using the `WAFFLE_FLAG_MODEL` configuration.

It would be useful to have analogous support for custom Switch models.

The work would likely involve creating a version of [get_waffle_flag_model](https://github.com/django-waffle/django-waffle/blob/4bb357d153e60ac567bd80f2c254389589ae4c6c/waffle/__init__.py#L33-L52) for switches.

**Comment by allanlewis** [comment]
Can this be closed now that #448 has been merged?
