### ISSUE TITLE
Configuration support to disable admin pages

### ISSUE THREAD

**Issue by onurhunce-planetly** [clintonb/django-waffle#443]
Waffle registers 3 admin pages by default:

```
admin.site.register(Flag, FlagAdmin)
admin.site.register(Sample, SampleAdmin)
admin.site.register(Switch, SwitchAdmin)
```

I think it would be nice to have a configuration parameter like: `WAFFLE_DISABLE_ADMIN_PAGES` to enable users of the library to easily implement custom admin pages or disable admin pages by default via one liner config (Since these pages give a lot of power to admin users)

When the need is appreciated by the others, I can create a pull request for this one.

**Comment by clintonb** [comment]
Feel free to open a pull request.

**Comment by onurhunce-planetly** [comment]
@clintonb  any comments are welcomed on the pr: https://github.com/django-waffle/django-waffle/pull/444

**Comment by onurhunce-planetly** [comment]
It is addressed via the following pr: https://github.com/django-waffle/django-waffle/pull/444

**Comment by onurhunce-planetly** [comment]
@clintonb would you mind having a new release for this one? I would be glad to pump the version and use this config in our repository :)
