### ISSUE TITLE
New view to expose flag state as JSON

### ISSUE THREAD

**Issue by shaungallagher** [clintonb/django-waffle#449]
Waffle currently has a view to expose flag state as Javascript via the WaffleJS endpoint.

But there are a number of use cases, e.g. backend API calls, where it would be preferable to expose that state in a serialized format like JSON.

For use cases like an audit dashboard, the view might also expose metadata such as the total number of active and and inactive flags of each type, and the number of stale flags (i.e. more than X days since last toggled).

I propose a new backend function that queries the database and returns this data, and a new endpoint that returns the data as JSON.

**Comment by clintonb** [comment]
Cool. Feel free to discuss here and/or open a pull request.

**Comment by cole-jacobs** [comment]
Awesome. With this merged, when do you plan to cut a new release? Looking forward to getting this from pypi.

**Comment by clintonb** [comment]
@cole-jacobs new release should hit PyPI in a few minutes.

**Comment by dancergraham** [comment]
completed in #452
