### ISSUE TITLE
`WAFFLE_SWITCH_MODEL` is missing from the "Configuring Waffle" docs page

### ISSUE THREAD

**Issue by allanlewis** [clintonb/django-waffle#454]
The setting `WAFFLE_SWITCH_MODEL` allows using a custom switch model. It's documented on the [Switches page](https://waffle.readthedocs.io/en/stable/types/switch.html#custom-switch-models) but not on the [Configuring Waffle page](https://waffle.readthedocs.io/en/stable/starting/configuring.html). For comparison, the equivalent setting for flags, `WAFFLE_FLAG_MODEL`, is documented on both the Flags and Configuring Waffle pages.

Perhaps there are other settings missing from the Configuring Waffle page? I haven't checked.

**Comment by clintonb** [comment]
Feel free to submit a pull request with a fix.

**Comment by allanlewis** [comment]
If someone can supply a description of `WAFFLE_SWITCH_MODEL` for the docs I'd be happy to raise a PR; I'm not sure how to describe it myself.

**Comment by dancergraham** [comment]
Suggested description:

WAFFLE_SWITCH_MODEL
The Django model that will be used for switches. Defaults to waffle.Switch, which provides basic switch functionality. This can be swapped for a custom Switch model if additional fields or behaviors are needed. The custom model must inherit from waffle.models.AbstractBaseSwitch.  Needs to be set at the start of a project, as Django’s migration framework does not support changing swappable models after the initial migration.
