### ISSUE TITLE
Auto-create Custom Switch Models

### ISSUE THREAD

**Issue by cole-jacobs** [clintonb/django-waffle#456]
Auto-creating custom switches fails with: `AttributeError: Manager isn't available; 'waffle.Switch' has been swapped for '<custom model>'`.

In models.py, the Flag version of `is_active` calls `get_waffle_flag_model` before its call to `get_or_create`. I think a similar pattern should be used for switches and samples. Happy to submit a patch for this tonight.

**Comment by clintonb** [comment]
Yes, please patch.

**Comment by cole-jacobs** [comment]
👌 I'll get something up soon. Just noticed the same idea can be added to `override_switch` and `override_sample`, so I'll include that as well.
