### ISSUE TITLE
No CHANGES entry for 3.0.0

### ISSUE THREAD

**Issue by robrap** [clintonb/django-waffle#464]
It looks like 3.0.0 was recently released, presumably with breaking changes(?), but there is no entry for it in: https://github.com/django-waffle/django-waffle/blob/master/CHANGES.

FYI: @clintonb (and Hello!)

**Comment by clintonb** [comment]
Hey Robert! Thanks for letting me know. This will be fixed by https://github.com/django-waffle/django-waffle/pull/465.

**Comment by robrap** [comment]
Thanks Clinton.
