### ISSUE TITLE
Improve api documentation

### ISSUE THREAD

**Issue by dancergraham** [clintonb/django-waffle#526]
The api is only partially documented in the online docs, for instance the flags page lists attributes (but capitalises them) and does not list methods - it would be good to document the public methods

https://waffle.readthedocs.io/en/stable/types/flag.html

[Switches ](https://waffle.readthedocs.io/en/stable/types/switch.html)lists neither attributes nor methods

[Samples](https://waffle.readthedocs.io/en/stable/types/sample.html) lists attributes (but capitalises them) and does not list methods

**Comment by yanurag-dev** [comment]
@dancergraham I would like to pick this issue.

**Comment by dancergraham** [comment]
Great, let me know if you need any help getting started

**Comment by yanurag-dev** [comment]
@dancergraham Hi, I'm currently busy with a task and unable to contribute this time, so I will unassign myself.
